"""
Summarization: ExtractedDocument -> DocumentSummary (title + summary).

Generic by design — same doc yields the same summary. Project-tailored output
is deferred; when needed, callers can subclass or extend the prompt context.

One LLM pass per call. For docs that exceed the budget we send head + tail
rather than spending more passes; map-reduce is a future optimization.
"""

from __future__ import annotations

import json
import logging

from src.utils.schemas import AssembledDocument, DocumentSummary, ExtractedDocument

# Either input is acceptable: AssembledDocument (corpus) has all the same structural
# fields as ExtractedDocument (uploads) plus a top-level title, and Summarizer only
# touches the shared fields.
SummarizerInput = ExtractedDocument | AssembledDocument

logger = logging.getLogger(__name__)

# Char budget for the LLM context. ~15k tokens, leaves headroom in a 128k window.
# Replace with proper tokenizer-aware trimming if/when we hit edge cases.
_MAX_CHARS = 60_000

# Cap how much of the budget the outline can take when body text is being dropped.
# Without it, a multi-hundred-entry TOC could push head/tail negative and corrupt
# the resulting context.
_OUTLINE_MAX_CHARS = _MAX_CHARS // 3


def _truncate_outline(outline: str, max_chars: int) -> str:
    """Cap the rendered outline at max_chars so it can't dominate the budget."""
    if len(outline) <= max_chars:
        return outline
    marker = "\n[... outline truncated ...]"
    keep = max_chars - len(marker)
    return outline[:keep] + marker if keep > 0 else marker.lstrip("\n")


def _render_outline(extracted: SummarizerInput) -> str:
    """
    Render a compact outline of the document for context when the body is truncated.

    Prefers extracted.toc (PDF bookmarks). Falls back to section headings from the
    layout extractor. Empty string if neither is available.
    """
    entries = []
    if extracted.toc:
        for e in extracted.toc:
            indent = "  " * max(0, (e.level or 1) - 1)
            page = f" (p. {e.page})" if e.page else ""
            entries.append(f"{indent}- {e.title}{page}")
    else:
        for s in extracted.sections:
            if not s.title:
                continue
            indent = "  " * max(0, (s.level or 1) - 1)
            page = f" (p. {s.page})" if s.page else ""
            entries.append(f"{indent}- {s.title}{page}")
    return "\n".join(entries)


def _build_summary_context(extracted: SummarizerInput, max_chars: int = _MAX_CHARS) -> str:
    """
    Build the LLM context: full text when it fits, otherwise head + outline + tail.

    For long docs the middle of the body is dropped but the section outline goes in
    its place, so the LLM still knows what topics live in the missing middle.
    """
    text = extracted.text
    if len(text) <= max_chars:
        return text

    outline = _truncate_outline(_render_outline(extracted), _OUTLINE_MAX_CHARS)
    outline_block = f"\n\n[Document outline]\n{outline}\n\n" if outline else "\n\n"
    marker = "[... middle of the document omitted; outline above shows structure ...]\n\n"
    available = max(0, max_chars - len(outline_block) - len(marker))
    head = available // 2
    tail = available - head
    # Guard: text[-0:] returns the whole string, not the empty string.
    head_text = text[:head] if head > 0 else ""
    tail_text = text[-tail:] if tail > 0 else ""
    return f"{head_text}{outline_block}{marker}{tail_text}"


def _looks_like_default_title(t: str) -> bool:
    """Filter out autogenerated metadata titles (Word/InDesign defaults, filenames)."""
    t = t.strip().lower()
    if not t:
        return True
    if t.endswith((".pdf", ".doc", ".docx")):
        return True
    return t in {"untitled", "document1", "microsoft word - document1", "document"}


class Summarizer:
    """
    Document-level analysis primitive.

    Accepts either an ExtractedDocument (uploaded PDF, single file) or an
    AssembledDocument (corpus article, multi-source assembly). Both expose the
    structural fields the title cascade and outline rendering need.

    Title cascade (no extra LLM call — title comes from the same single pass
    when nothing higher up in the cascade gives a usable one):
      0. Top-level .title attribute        (AssembledDocument only — corpus title from the API)
      1. pdf_metadata.title                (PyMuPDF, often empty)
      2. First top-level section title     (docling usually nails this)
      3. LLM-emitted title from the summary call
    """

    def __init__(self, llm, prompts: dict, organization: str, language: str = "nl"):
        self.llm = llm
        self.prompts = prompts
        self.organization = organization
        self.language = language

    def summarize(
        self,
        extracted: SummarizerInput,
        language: str | None = None,
    ) -> DocumentSummary:
        """
        Run the title cascade + one LLM summary call, return DocumentSummary.

        Raises RuntimeError if the LLM call fails, returns an unparseable response,
        or yields an empty summary. The caller (BWAnalyzer.summarize_document) relies
        on this so a transient LLM failure can't poison the persisted cache with
        an empty result.
        """
        lang = language or self.language
        llm_title, summary = self._llm_title_and_summary(extracted, lang)
        if not summary:
            raise RuntimeError(
                "Summarizer produced no summary (LLM call failed or response was unparseable)"
            )
        title = self._resolve_title(extracted, llm_title)
        return DocumentSummary(title=title, summary=summary)

    # ------------------------------------------------------------------ internal

    def _llm_title_and_summary(
        self, extracted: SummarizerInput, language: str
    ) -> tuple[str | None, str]:
        context = _build_summary_context(extracted)
        if not context.strip():
            logger.warning("summarize_document: empty extracted text")
            return None, ""

        system = self.prompts["summarize_document"]["system"][language].format(
            organization=self.organization,
            reply_language=language,
            context=context,
        )
        user = self.prompts["summarize_document"]["human"][language]

        llm_response = self.llm.prompt(user, system=system)
        if llm_response.error:
            logger.error("summarize_document LLM failed: %s", llm_response.exception)
            return None, ""
        return self._parse_summary(llm_response.raw_response.strip())

    @staticmethod
    def _parse_summary(raw: str) -> tuple[str | None, str]:
        if raw.startswith("```"):
            raw = raw.split("```", 2)[1].lstrip("json").strip()
        try:
            data = json.loads(raw)
        except Exception as e:
            logger.error("summarize_document JSON parse failed: %s\n%s", e, raw)
            return None, ""
        if not isinstance(data, dict):
            logger.error("summarize_document unexpected JSON structure: %s", type(data).__name__)
            return None, ""
        title = data.get("title")
        summary = data.get("summary", "")
        if not isinstance(summary, str):
            summary = str(summary)
        title_clean = title.strip() if isinstance(title, str) and title.strip() else None
        return title_clean, summary.strip()

    @staticmethod
    def _resolve_title(extracted: SummarizerInput, llm_title: str | None) -> str | None:
        # 0. AssembledDocument carries an explicit top-level title (set by the source
        #    API for corpus docs). ExtractedDocument has no such field; getattr handles
        #    both shapes.
        top_title = getattr(extracted, "title", None)
        if isinstance(top_title, str) and top_title.strip():
            t = top_title.strip()
            if not _looks_like_default_title(t):
                return t
        if extracted.pdf_metadata and extracted.pdf_metadata.title:
            t = extracted.pdf_metadata.title.strip()
            if t and not _looks_like_default_title(t):
                return t
        for s in extracted.sections:
            if s.title and (s.level is None or s.level <= 1):
                t = s.title.strip()
                if t:
                    return t
        return llm_title
