// apps/backend/src/templates/themeTemplates.ts

import { ITheme } from '@shared/types';

export enum ThemeTemplateEnum {
  DEFAULT = 'DEFAULT',
  V1_1 = 'V1_1',
}

export const themeTemplates: Record<ThemeTemplateEnum, Partial<ITheme>[]> = {
  [ThemeTemplateEnum.DEFAULT]: [
    { name: 'Subjectief welzijn', description: 'Subjectief welzijn gaat om de tevredenheid met het leven en de mate van ervaren regie over het eigen leven. Mensen streven niet alleen naar financiële stabiliteit, maar ook naar een breder gevoel van controle en autonomie. Een samenleving waarin brede welvaart wordt nagestreefd, biedt kansen waarmee individuen en groepen zich kunnen blijven ontwikkelen en zich beter kunnen aanpassen aan veranderingen (een leven lang leren). Het is daarmee niet alleen gericht is op materiële welvaart, maar ook op persoonlijke groei en tevredenheid. ' },
    { name: 'Gezondheid', description: 'Gezondheid gaat over fysieke en mentale gezondheid. Het gaat over het hebben van gezonde jaren, ervaren gezondheid en levensverwachting. Gezondheid kan worden beïnvloed door bijvoorbeeld overgewicht, eenzaamheid of stress. Gezondheid gaat ook over actief en volwaardig deel kunnen nemen aan de samenleving met of zonder beperking. ' },
    { name: 'Consumptie en Inkomen', description: 'Consumptie en inkomen gaat over de financiële situatie op het persoonlijk vlak. Het gaat hierbij zowel om inkomstensbronnen als om consumptiemogelijkheden. Het betreft de individuele keuze en mogelijkheid om diensten en goederen te kiezen, het opbouwen of hebben van een financiële buffer en de ruimte om een eigen levensstijl te onderhouden. Dit inclusief keuzemogelijkheden in onderwijs en gezondheidszorg. ' },
    { name: 'Onderwijs en opleiding', description: 'Onderwijs en opleiding bevat alle onderdelen van overdracht van kennis, leren van vaardigheden en socialisatie op alle leeftijden. Het bevat zowel officiële en onofficiële kennisoverdrachten. Denk aan stages, verenigingen, opleidingen, cursussen of algemene scholing, maar ook informele leermogelijkheden zoals onderdeel zijn van een jeugdteam of het leren van een muziekinstrument. Het gaat ook over de randvoorwaarden voor onderwijs en opleiding, zoals het aantrekken en behouden van onderwijzend personeel, goede schoolgebouwen, digitale infrastructuur, etc. ' },
    { name: 'Ruimtelijke samenhang en kwaliteit', description: 'Een kwalitatief goede inrichting van de ruimte is een belangrijke randvoorwaarde voor de ervaren brede welvaart. Ruimtelijke Samenhang en Kwaliteit gaat over de staat en gebruik van de bebouwde en onbebouwde omgeving. De inrichting en samenhang is gericht op nu en de toekomst. Ruimtelijke samenhang draagt bij aan een kwalitatieve beleving van stad, omgeving of aanzicht. Denk bijvoorbeeld aan bereikbaarheid, faciliteiten in de omgevingen en tevredenheid over groene ruimte. ' },
    { name: 'Economisch kapitaal', description: 'Economisch kapitaal omvat de verschillende vormen van kapitaal op macroniveau, die nodig zijn voor het opbouwen van materiële welvaart en het genereren van economische groei. Het gaat over bedrijfsvestigingen en aantrekkelijkheid voor bedrijven, werkloosheid, werkgelegenheid, vermogens en vermogensongelijkheid binnen de eigen gemeente maar ook in vergelijking met andere gemeentes. ' },
    { name: 'Natuurlijk kapitaal', description: 'Natuurlijk kapitaal gaat om een schone, groene, biodiverse leefomgeving hier en nu, denk aan schoon drinkwater, schone lucht en voldoende kwalitatief groen in de stad. Het gaat enerzijds dat de stad behouden moet worden voor de toekomst, anderzijds dat de leefomstandigheden op de planeet gunstig moeten blijven voor de mensheid en al het andere leven. Denk aan CO2-vermindering, het beschermen van ecosystemen, het duurzaam gebruik van natuurlijke hulpbronnen nu en in de toekomst. ' },
    { name: 'Sociaal kapitaal', description: 'Sociaal kapitaal gaat over het verbonden voelen met anderen. Belangrijk zijn sociale netwerken (online en fysiek) die zorgen voor toegang tot informatie en het hebben of maken van een sociaal vangnet. Het gaat om verenigingsgevoel, sociale cohesie, veiligheid om te zijn wie je bent en groepsvorming (bijvoorbeeld met verenigingen of binnen een geloofsovertuigingen). Ook gaat dit thema om vertrouwen in mensen en instituties, maar ook over (financiële) ongelijkheden tussen mensen en groepen.' },
    { name: 'Veiligheid', description: 'Veiligheid gaat in op de mate waarin overlast, ondermijning en criminaliteit plaatsvinden in de stad en online. Het is een breed spectrum met onder meer hoge-impact-criminaliteit, cybercriminaliteit, druggerelateerde criminaliteit, huiselijk geweld, seksueel geweld en intimidatie, discriminatie en racisme. Het gaat ook over veiligheid verbeteren, overlast terugdringen en slachtoffers helpen. Zowel in de stad (thuis en in de openbare ruimte) als Amsterdammers online. In Amsterdam wordt sociale veiligheid gezien als randvoorwaarde voor een vrije stad. Dat je je veilig voelt, is belangrijk. ' },
    { name: 'Wonen', description: 'Een goede betaalbare woonruimte is één van de eerste levensbehoeften. Niet iedereen kan op dit moment aan een woning komen die bij haar/zijn/hen situatie past. Het gaat over de kwaliteit van de woning (incl duurzaamheid) en tevredenheid met de woning en woonomgeving. Daarnaast ook de ervaren overlast in/nabij de woning en de woonlasten. Ook de druk op de woningmarkt speelt hier een belangrijke rol (hoe moeilijk komen verschillende doelgroepen aan een woning). ' },
  ],
  // Scan v1.1 — theme names and definitions per SRDO-3634 (juli 2026)
  [ThemeTemplateEnum.V1_1]: [
    { name: 'Welzijn', description: 'Welzijn gaat om de tevredenheid met het leven en de mate van ervaren regie over het eigen leven. Mensen streven niet alleen naar financiële stabiliteit, maar ook naar een breder gevoel van controle, autonomie en zelfredzaamheid. Een samenleving waarin brede welvaart wordt nagestreefd, biedt kansen waarmee individuen en groepen zich kunnen blijven ontwikkelen, zich beter kunnen aanpassen aan veranderingen en gelukkig kunnen zijn. Dit thema is daarmee gericht op persoonlijke groei en tevredenheid.' },
    { name: 'Gezondheid', description: 'Gezondheid gaat over fysieke en mentale gezondheid. Het gaat over het hebben van gezonde jaren, ervaren gezondheid en levensverwachting. Gezondheid kan worden beïnvloed door bijvoorbeeld overgewicht, eenzaamheid of stress. Gezondheid gaat ook over actief en volwaardig deel kunnen nemen aan de samenleving met of zonder beperking.' },
    { name: 'Arbeid', description: 'Arbeid gaat over de financiële situatie op het persoonlijk vlak. Het gaat hierbij om inkomstensbronnen, schulden, consumptie- en werkmogelijkheden. Het betreft de individuele keuze en mogelijkheid om diensten en goederen te kiezen, het opbouwen of hebben van een financiële buffer en de ruimte om een eigen levensstijl te onderhouden. Dit inclusief keuzemogelijkheden in onderwijs en gezondheidszorg.' },
    { name: 'Menselijk kapitaal', description: 'Menselijk kapitaal bevat alle onderdelen van overdracht van kennis, leren van vaardigheden en socialisatie op alle leeftijden. Het bevat zowel officiële en onofficiële kennisoverdrachten. Denk aan stages, verenigingen, opleidingen, cursussen of algemene scholing, maar ook informele leermogelijkheden zoals onderdeel zijn van een (jeugd)team of het leren van een muziekinstrument. Het gaat ook over de randvoorwaarden voor onderwijs en opleiding, zoals het aantrekken en behouden van onderwijzend personeel, goede schoolgebouwen, digitale infrastructuur, etc.' },
    { name: 'Ruimte', description: 'Een kwalitatief goede inrichting van de ruimte is een belangrijke randvoorwaarde voor de ervaren brede welvaart. Het thema ruimte gaat over de staat en gebruik van de bebouwde en onbebouwde omgeving. Ruimtelijke samenhang draagt bij aan een kwalitatieve beleving van stad, omgeving of aanzicht. Denk bijvoorbeeld aan bereikbaarheid, mobiliteit, faciliteiten in de omgevingen en tevredenheid over groene ruimte.' },
    { name: 'Economisch kapitaal', description: 'Economisch kapitaal omvat de verschillende vormen van kapitaal op macroniveau, die impact hebben op het opbouwen van materiële welvaart en het genereren van economische groei. Het gaat over bedrijfsvestigingen en aantrekkelijkheid voor bedrijven, werkloosheid, werkgelegenheid, vermogens en vermogensongelijkheid binnen de eigen gemeente, maar ook in de regio en andere gemeentes.' },
    { name: 'Milieu & Natuurlijk kapitaal', description: 'Milieu en natuurlijk kapitaal draait om een schone, groene en biodiverse leefomgeving, zowel nu als in de toekomst. Dit omvat schoon drinkwater, schone lucht en voldoende kwalitatief groen in de stad. Het gaat enerzijds om de leefbaarheid van de stad en het behoud daarvan voor toekomstige generaties. Anderzijds gaat het om de impact van menselijk handelen op de planeet en al het andere leven. Denk hierbij aan het verminderen van CO2-uitstoot, het beschermen van ecosystemen en het duurzaam gebruik van natuurlijke hulpbronnen.' },
    { name: 'Samenleving en sociaal kapitaal', description: 'Samenleving en sociaal kapitaal gaat over het verbonden voelen met anderen. Belangrijk zijn sociale netwerken (online en fysiek) die zorgen voor toegang tot informatie en het hebben of maken van een sociaal vangnet. Dit thema gaat om verenigingsgevoel, sociale cohesie, veiligheid om te zijn wie je bent en groepsvorming (bijvoorbeeld verenigingen of geloofsovertuigingen). Ook gaat dit thema om vertrouwen in mensen en instituties, maar ook over (financiële) ongelijkheden tussen mensen en groepen.' },
    { name: 'Veiligheid', description: 'Veiligheid gaat over de mate waarin overlast, ondermijning en criminaliteit plaatsvinden in de stad en online. Het is een breed spectrum met onder meer hoge-impact-criminaliteit, cybercriminaliteit, druggerelateerde criminaliteit, huiselijk geweld, seksueel geweld en intimidatie, discriminatie en racisme. Het gaat ook over veiligheid verbeteren, overlast terugdringen en slachtoffers helpen. Zowel in de stad (thuis en in de openbare ruimte) als Amsterdammers online.' },
    { name: 'Wonen', description: 'Een goede betaalbare woonruimte is één van de eerste levensbehoeften. Niet iedereen kan op dit moment aan een woning komen die bij haar/zijn/hen situatie past. Het gaat over de kwaliteit van de woning (incl duurzaamheid) en tevredenheid met de woning en woonomgeving. Daarnaast ook de ervaren overlast in/nabij de woning en de woonlasten. Ook de druk op de woningmarkt speelt hier een belangrijke rol (hoe moeilijk komen verschillende doelgroepen aan een woning).' },
  ],
};
